# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines

pool:
  vmImage: ubuntu-latest

# container:
#  image: registry.redhat.io/advanced-cluster-security/rhacs-roxctl-rhel8:3.71
#  endpoint: registry.redhat.io
#  options: --entrypoint="" # inneffectual

# https://mirror.openshift.com/pub/rhacs/assets/latest/bin/Linux/roxctl
jobs:

  - job: RHACS-Image-Scan
    steps:
      - script: |
          curl -O https://mirror.openshift.com/pub/rhacs/assets/latest/bin/Linux/roxctl
          chmod 755 roxctl
        displayName: 'Download latest roxctl'

      - script: |
          mkdir $(System.DefaultWorkingDirectory)/artifacts
          ./roxctl image scan -e $ROX_CENTRAL_ENDPOINT --image vulnerables/cve-2017-7494 --format csv > $(System.DefaultWorkingDirectory)/artifacts/image_scan.csv
          ./roxctl image check -e $ROX_CENTRAL_ENDPOINT --image vulnerables/cve-2017-7494 > $(System.DefaultWorkingDirectory)/artifacts/image_check.txt
        displayName: 'RHACS image scan'
        env: 
          ROX_API_TOKEN: $(rox-api-token)
          ROX_CENTRAL_ENDPOINT: '$(rox-central-endpoint)'
        