# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

container:
  image: registry.redhat.io/advanced-cluster-security/rhacs-roxctl-rhel8:3.71
  endpoint: registry.redhat.io
  options: --entrypoint=""
  
steps:
- script: /usr/bin/roxctl --help
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
