# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

# container:
#  image: registry.redhat.io/advanced-cluster-security/rhacs-roxctl-rhel8:3.71
#  endpoint: registry.redhat.io
#  options: --entrypoint="" # inneffectual

# https://mirror.openshift.com/pub/rhacs/assets/latest/bin/Linux/roxctl
jobs:
  - job: GetRoxctl
    steps:
      - script: |
          curl -O https://mirror.openshift.com/pub/rhacs/assets/latest/bin/Linux/roxctl
          chmod 755 roxctl
        displayName: 'Download latest roxctl'

  - job: TestRoxctl
    steps:
      - script: ./roxctl --help
        displayName: 'Attempt roxctl exec'
